name: TEMPLATE-PLUGIN
version: '${version}'
main: org.example.ikknight.templatep.Main
api-version: '1.20'
commands:
  reloadtp:
    description: reloads this plugins configuration (PERMISSIONS --> OP)
    usage: /<command>

